<?php
$this->headScript()->prependFile($this->basePath() . '/js/delete.js', 'text/javascript');
$title = 'Lanternas Verdes ';
$this->headTitle($title);
$this->placeholder('url')->edit = $this->urlEdit;
$this->placeholder('url')->delete = $this->urlDelete;
$this->partialLoop()->setObjectKey('model');
?>
<h1><?=$this->escapeHtml($title)?></h1>
<p>
    <a href="<?=$this->url(
        'tropa',
         [
             'action'=>'edit',
             'controller'=>'lanterna'
            ]
        )?>">Novo Lanterna Verde</a>
</p>
<table class="table">
<tr>
    <th>Código</th>
    <th>Nome</th>
    <th>Setor</th>
    <th>&nbsp;</th>
</tr>
<?=$this->partialLoop('lanternas.phtml', $this->paginator) ?>
</table>
<p>
<?=$this->paginationControl($this->paginator,
                                    'Sliding',
                                    'pagination', ['route' => $this->route, 'controller' => $this->controller]); ?>
</p>
<p>
    <a href="<?=$this->urlHomepage?>">Homepage</a>
</p>