<tr>
    <td><?=$this->model->codigo?></td>
    <td><?=$this->escapeHtml($this->model->nome)?></td>
    <td><?=$this->escapeHtml($this->model->setor->nome)?></td>
    <td>
        <a href="<?=$this->placeholder('url')->edit . '/' . $this->model->codigo?>">Editar</a>
        <button class="delete" url="<?=$this->placeholder('url')->delete . '/' . $this->model->codigo?>">Remover</button>
    </td>
</tr>