<?php
$this->headScript()->prependFile($this->basePath() . '/js/delete.js', 'text/javascript');
$title = 'Setores ';
$this->headTitle($title);
$this->placeholder('url')->edit = $this->urlEdit;
$this->placeholder('url')->delete = $this->urlDelete;
$this->partialLoop()->setObjectKey('model');
?>
<h1><?=$this->escapeHtml($title)?></h1>
<p>
    <a href="<?=$this->urlEdit?>">Novo setor</a>
</p>
<table class="table">
<tr>
    <th>Código</th>
    <th>Nome</th>
    <th>&nbsp;</th>
</tr>
<?=$this->partialLoop('setores.phtml', $this->paginator) ?>
</table>
<?=$this->paginationControl($this->paginator,
                                    'Sliding',
                                    'pagination', ['route' => $this->route, 'controller' => $this->controller]); ?>
<p>
    <a href="<?=$this->urlHomepage?>">Homepage</a>
</p>